//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBidWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBid()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int BidID { get; set; }
        public string bid_Name { get; set; }
        public string bid_Description { get; set; }
        public Nullable<long> bid_MINamount { get; set; }
        public string bid_Image { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> bid_endTime { get; set; }
        public Nullable<int> QTY { get; set; }

        public Nullable<byte> Status { get; set; }
        public virtual tblbidcategory tblbidcategory { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
