//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBidWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int Contact_Id { get; set; }
        public string Contact_name { get; set; }
        public string Contact_subject { get; set; }
        public string Contact_email { get; set; }
        public string Contact_phone { get; set; }
        public string Contact_message { get; set; }
    }
}
