//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBidWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_getallproducts
    {
        public int ProID { get; set; }
        public string pro_Name { get; set; }
        public string Category { get; set; }
        public string pro_Description { get; set; }
        public Nullable<int> pro_price { get; set; }
        public string pro_Image { get; set; }
    }
}
